chore: update styles for <Spinner /> to newest specs
aragon/ods pull request #133
Opened 2024-04-01 09:59 UTC by thekidnamedkd

## Description

Updates "neutral" style to new monochrome look, adds new "primary_inverted" variant

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

## Checklist:

-   [x] I have selected the correct base branch.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] I have made corresponding changes to the documentation.
-   [x] My changes generate no new warnings.
-   [x] Any dependent changes have been merged and published in downstream modules.
-   [x] I ran all tests with success and extended them if necessary.
-   [x] I have updated the `CHANGELOG.md` file in the root folder of the package after the [UPCOMING] title and before
        the latest version.
-   [x] I have tested my code on the test network.

2024-05-15 09:33 UTC, Fabricevladimir approved these changes
LGTM! Don't forget to rebase and fix the changelog conflicts

2024-05-15 09:33 UTC, Fabricevladimir commented on src/core/components/spinner/spinner.tsx
> +export type SpinnerVariant = 'neutral' | 'primary' | 'primary_inverse' | 'success' | 'warning' | 'critical';
Are you certain that the inverse is only for the primary?

2024-05-15 14:30 UTC, Fabricevladimir reviewed
Need to sync with design

2024-05-15 14:31 UTC, Fabricevladimir requested changes
Need to sync with design

2024-05-28 06:55 UTC, cgero-eth commented
Closing as updates have been merged into https://github.com/aragon/ods/pull/194

2024-05-28 06:55 UTC, closed without merging